language: php
php:
  - "5.5"
  - "5.4"
  - "5.6"
  - "7.0"
  - "7.1"
script: 
    - sed -e "s#@YOUR_PARTNER_ID@#$PARTNER_ID#g" -e "s#@YOUR_ADMIN_SECRET@#$ADMIN_SECRET#g" TestCode/config.template.ini > TestCode/config.ini 
    - cd TestCode/ && php TestMain.php 
notifications:
  email:
    recipients:
      - moshe.maor@kaltura.com
      - jess.portnoy@kaltura.com
      - Jonathan.Kanarek@kaltura.com
    on_success: change
    on_failure: always
